

fruits = ["APPLE", "BANANA", "CHERRY", "DATE", "ELDERBERRY", "FIG", "GRAPE", "GUAVA", "JACKFRUIT", "KIWI", "LEMON", "MANGO", "MELON", "NECTARINE", "ORANGE", "PAPAYA", "PEAR", "PINEAPPLE", "POMEGRANATE", "QUINCE", "RASPBERRY", "STRAWBERRY", "TANGERINE", "WATERMELON"]

